"""Adding Dates In ToDo Table

Revision ID: cc17e3c9f061
Revises: a0a9a329709c
Create Date: 2020-02-11 18:08:21.359498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc17e3c9f061'
down_revision = 'a0a9a329709c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoitems', sa.Column('date_completed', sa.DateTime(), nullable=True))
    op.add_column('todoitems', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoitems', 'date_updated')
    op.drop_column('todoitems', 'date_completed')
    # ### end Alembic commands ###
